version: "3"
services:
  twitflow:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TWITTER_API_BEARER_TOKEN=${TWITTER_API_BEARER_TOKEN}
    healthcheck:
      test: "exit 0"
